-- MySQL Script generated by MySQL Workbench
-- Thu 21 Nov 2019 01:44:07 WAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vh_premium_class_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vh_premium_class_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vh_premium_class_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vh_premium_class_db` ;

-- -----------------------------------------------------
-- Table `vh_premium_class_db`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vh_premium_class_db`.`teachers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vh_premium_class_db`.`premium_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vh_premium_class_db`.`premium_classes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `teacher_id` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `teacher_id` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `premium_classes_ibfk_1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `vh_premium_class_db`.`teachers` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vh_premium_class_db`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vh_premium_class_db`.`sessions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `class_id` INT(11) NOT NULL,
  `teacher_id` INT(11) NULL DEFAULT NULL,
  `date` DATE NOT NULL,
  `start` TIME NOT NULL,
  `time_zone` VARCHAR(255) NOT NULL,
  `duaration` INT(11) NOT NULL,
  `link` VARCHAR(500) NULL DEFAULT NULL,
  `status` VARCHAR(255) NOT NULL,
  `session_file` BLOB NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `premium_class_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `teacher_id` (`teacher_id` ASC) VISIBLE,
  INDEX `premium_class_id` (`premium_class_id` ASC) VISIBLE,
  CONSTRAINT `sessions_ibfk_1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `vh_premium_class_db`.`teachers` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `sessions_ibfk_2`
    FOREIGN KEY (`premium_class_id`)
    REFERENCES `vh_premium_class_db`.`premium_classes` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vh_premium_class_db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vh_premium_class_db`.`students` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `membership` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vh_premium_class_db`.`attendances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vh_premium_class_db`.`attendances` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `session_id` INT(11) NULL DEFAULT NULL,
  `student_id` INT(11) NULL DEFAULT NULL,
  `mode` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `session_id` (`session_id` ASC) VISIBLE,
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `attendances_ibfk_1`
    FOREIGN KEY (`session_id`)
    REFERENCES `vh_premium_class_db`.`sessions` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `attendances_ibfk_2`
    FOREIGN KEY (`student_id`)
    REFERENCES `vh_premium_class_db`.`students` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
